### ISSUE TITLE
Setup MQTT Server

### ISSUE THREAD

**Issue by josalhor** [JoanPalau/biometric-monitor-framework#1]
*As a* developer
*I want to* setup the MQTT Server
*In order to* receive the data and relay it to the consumer

***
**Requirements**
* Setup the MQTT Server and get the credentials

**Task Completion Checklist**
- [ ] Decide on a local MQTT Server or a Remote MQTT Server
- [ ] Download and install the server (if local) or sign up and register (if remote)
- [ ] Get the credentials for setting up MQTT
