### ISSUE TITLE
Develop ESP-32 MQTT Connection 

### ISSUE THREAD

**Issue by josalhor** [JoanPalau/biometric-monitor-framework#10]
*As a* dev
*I want to* be able to subscribe to data of the MQTT Server by the ESP-32
*In order to* collect the data from the sensor

***
**Requirements**
* Create a set of functions that can be deployed on all the consumer of the MQTT channels

**Dependencies**
* #1 

**Task Completion Checklist**
- [ ] Performed research about the components (voltatges, connections, requirements etC)
- [ ] Installed libraries and drivers
- [ ] Diagram of the components done
- [ ] Developed program 
- [ ] Deployed program to Arduino
- [ ] Tested program as necessary
