### ISSUE TITLE
ML model for class

### ISSUE THREAD

**Issue by josalhor** [JoanPalau/biometric-monitor-framework#16]
*As a* dev
*I want to* I want to study a ML model
*In order to* present a reasonable summary of 

***
**Requirements**
* Present the ML model study

**Task Completion Checklist**
- [ ] Performed research about the components (voltatges, connections, requirements etC)
- [ ] Installed libraries and drivers
- [ ] Developed program 
- [ ] Tested program as necessary
