### ISSUE TITLE
Setup HearthRate Collector

### ISSUE THREAD

**Issue by josalhor** [JoanPalau/biometric-monitor-framework#2]
*As a* dev
*I want to* setup the HearthRate Collector
*In order to* collect data about the hearth

***
**Requirements**
* Collect the Hearth Rate Sensor Data
* Send the sensor data to the MQTT Server

**Dependencies**
* #1 

**Task Completion Checklist**
- [ ] Performed research about the components (voltatges, connections, requirements etC)
- [ ] Installed libraries and drivers
- [ ] Diagram of the components done
- [ ] Developed program 
- [ ] Deployed program to Arduino
- [ ] Tested program as necessary
