### ISSUE TITLE
Connect Mobile App to DB

### ISSUE THREAD

**Issue by JoanPalau** [JoanPalau/biometric-monitor-framework#23]
*As a* dev
*I want to* create the needed endpoints
*In order to*fetch the data from the database

***
**Requirements**
* Can store new data fetched from the MQTT broker
* Can obtain all historic data

**Task Completion Checklist**
- [x] Installed libraries and drivers
- [x] Developed program 
- [x] Passes npm run build
- [x] Tested program as necessary
