### ISSUE TITLE
Display Live Data from the MQTT server in Mobile App

### ISSUE THREAD

**Issue by JoanPalau** [JoanPalau/biometric-monitor-framework#24]
*As a* dev
*I want to* display activity prediction and heart rate data available
*In order to* provide a more user friendly interface

***
**Requirements**
* Obtain the latest data received

**Task Completion Checklist**
- [x] Installed libraries and drivers
- [x] Developed program 
- [x] Passes npm run build
- [x] Tested program as necessary
