### ISSUE TITLE
Display Activity Data in Mobile App

### ISSUE THREAD

**Issue by JoanPalau** [JoanPalau/biometric-monitor-framework#25]
*As a* dev
*I want to* display all historic activity data available
*In order to* display them to the user

***
**Requirements**
* Store Activity data into a db
* Obtain data displaying the last value obtained on the top of the list
* Generatesome data samples

**Task Completion Checklist**
- [x] Installed libraries and drivers
- [x] Developed program 
- [x] Passes npm run build
- [x] Tested program as necessary
