### ISSUE TITLE
Setup the LCD Display for the ESP-32

### ISSUE THREAD

**Issue by josalhor** [JoanPalau/biometric-monitor-framework#8]
*As a* dev
*I want to* setup the LCD Display to the ESP-32
*In order to* display the user's health problems

***
**Requirements**
* Receive data about a given risk statistic
* Display that data with the LCD Display

**Task Completion Checklist**
- [ ] Performed research about the components (voltatges, connections, requirements etC)
- [ ] Installed libraries and drivers
- [ ] Diagram of the components done
- [ ] Developed program 
- [ ] Deployed program to Arduino
- [ ] Tested program as necessary
