### ISSUE TITLE
Setup a Machine Learning model to predict health problems

### ISSUE THREAD

**Issue by josalhor** [JoanPalau/biometric-monitor-framework#9]
*As a* dev
*I want to* setup a ML model to predict health problems
*In order to* display them to the user

***
**Requirements**
* Given a set Hearth Rate data and Accelometer data over time, predict health problems about the user

**Task Completion Checklist**
- [ ] Installed libraries and drivers
- [ ] Developed program 
- [ ] Deployed program to Arduino
- [ ] Tested program as necessary
